src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * A person (alive, dead, undead, or fictional).
 *
 * @see https://schema.org/Person Documentation on Schema.org
 *
 * @ORM\Entity
 *
 */
class Person
{
    protected static $genderMap = [
        'F' => 'female',
        'M' => 'male',
    ];

    protected static $iconMap = [
        'JABGB' => 'location-pin',
        'JCB' => 'book-skull',
        'QGJ' => 'box-archive',
        'MBNR' => 'newspaper',
        'SSWD' => 'square',
        'Buber' => 'envelope-open-text',
        'DBIO' => 'book',
    ];

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $status = 0;

    /**
     * @var string Additional name forms.
     *
     * @ORM\Column(name="alternate_name", nullable=true)
     */
    public $alternateName;

    /**
     * @var string A short description of the item.
     *
     * @ORM\Column(name="description", type="string", nullable=true)
     *
     */
    protected $description;

    /**
     * @var string A description of the item.
     *
     * @ORM\Column(name="disambiguating_description", type="string", length=4096, nullable=true)
     *
     */
    public $disambiguatingDescription;

    /**
     * @var string An additional name for a Person, can be used for a middle name.
     *
     */
    protected $additionalName;

    /**
     * @var string Date of birth.
     *
     * @ORM\Column(type="string", nullable=true)
     */
    public $birthDate;

    /**
     * @var string Date of death.
     *
     * @ORM\Column(type="string", nullable=true)
     */
    public $deathDate;

    /**
     * @var string Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.
     *
     * @ORM\Column(name="family_name", nullable=true)
     */
    public $familyName;

    /**
     * @var string The name of the item.
     *
     * @ORM\Column(name="name", nullable=false)
     */
    protected $name;

    /**
     * @var string Gender of the person.
     *
     * @ORM\Column(name="gender", nullable=true)
     */
    public $gender;

    /**
     * @var string Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.
     *
     * @ORM\Column(name="given_name", nullable=true)
     */
    public $givenName;

    /**
     * @var string Name of the birthPlace.
     *
     * @ORM\Column(nullable=true,name="birth_place")
     */
    public $birthPlaceLabel;

    /**
     * @var string Name of the deathPlace.
     *
     * @ORM\Column(nullable=true,name="death_place")
     */
    public $deathPlaceLabel;

    /**
     * @var string
     *
     * @ORM\Column(name="honorific_prefix", nullable=true)
     */
    public $honorificPrefix;

    /**
     * @var string
     *
     * @ORM\Column(name="honorific_suffix", nullable=true)
     */
    public $honorificSuffix;

    /**
     * @var string
     *
     * @ORM\Column(name="occupation", nullable=true)
     */
    public $hasOccupation;

    /**
     * @var int The data provider property
     *
     * @ORM\Column(name="data_provider", nullable=false)
     */
    public $dataProvider;

    /**
     * @var string The identifier property (external ID)
     *
     * @ORM\Column(name="identifier", nullable=false)
     */
    public $identifier;

    /**
     * @var string URL of the item
     *
     * @ORM\Column(nullable=true)
     */
    public $url;

    /**
     *  @var array external identifiers for this person
     * @ORM\Column(name="same_as", type="json")
     */
    public $sameAs = [];

    /**
     * Gets id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets additionalName.
     *
     * @param string $additionalName
     *
     * @return $this
     */
    public function setAdditionalName($additionalName)
    {
        $this->additionalName = $additionalName;

        return $this;
    }

    /**
     * Gets additionalName.
     *
     * @return string
     */
    public function getAdditionalName()
    {
        return $this->additionalName;
    }

    /**
     * Sets name.
     *
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string
     */
    public function getName()
    {
        if (empty($name)) {
            $this->name = $this->getFullname();
        }

        return $this->name;
    }

    /**
     * Sets birthDate.
     *
     * @param string $birthDate
     *
     * @return $this
     */
    public function setBirthDate($birthDate = null)
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    /**
     * Gets birthDate.
     *
     * @return string
     */
    public function getBirthDate()
    {
        return $this->birthDate;
    }

    /**
     * Sets deathDate.
     *
     * @param string $deathDate
     *
     * @return $this
     */
    public function setDeathDate($deathDate = null)
    {
        $this->deathDate = $deathDate;

        return $this;
    }

    /**
     * Gets deathDate.
     *
     * @return string
     */
    public function getDeathDate()
    {
        if (is_null($this->deathDate) || '0000-00-00' == $this->deathDate) {
            return null;
        }

        return $this->deathDate;
    }

    /**
     * Gets deathCause.
     *
     * @return string
     */
    public function getDeathCause()
    {
        return $this->deathCause;
    }

    /**
     * Sets familyName.
     *
     * @param string $familyName
     *
     * @return $this
     */
    public function setFamilyName($familyName)
    {
        $this->familyName = $familyName;

        return $this;
    }

    /**
     * Gets familyName.
     *
     * @return string
     */
    public function getFamilyName()
    {
        return $this->familyName;
    }

    /**
     * Sets gender.
     *
     * @param string $gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->gender = mb_strtoupper($gender);

        return $this;
    }

    /**
     * Gets gender.
     *
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    public function getGenderLabel()
    {
        $ret = $this->gender;

        if (!is_null($ret) && array_key_exists($ret, self::$genderMap)) {
            $ret = self::$genderMap[$ret];
        }

        return $ret;
    }

    /**
     * Sets givenName.
     *
     * @param string $givenName
     *
     * @return $this
     */
    public function setGivenName($givenName)
    {
        $this->givenName = $givenName;

        return $this;
    }

    /**
     * Gets givenName.
     *
     * @return string
     */
    public function getGivenName()
    {
        return $this->givenName;
    }

    /**
     * Sets nationality.
     *
     * @param string $nationality
     *
     * @return $this
     */
    public function setNationality($nationality)
    {
        $this->nationality = $nationality;

        return $this;
    }

    /**
     * Gets nationality.
     *
     * @return string
     */
    public function getNationality()
    {
        return $this->nationality;
    }

    /**
     * Sets birthPlace.
     *
     * @param Place $birthPlace
     *
     * @return $this
     */
    public function setBirthPlace(/* Place */ $birthPlace = null)
    {
        $this->birthPlace = $birthPlace;

        return $this;
    }

    /**
     * Gets birthPlace.
     *
     * @return Place
     */
    public function getBirthPlace()
    {
        return $this->birthPlace;
    }

    /**
     * Gets birthPlace.
     *
     * @return string
     */
    public function getBirthPlaceLabel()
    {
        return $this->birthPlaceLabel;
    }

    /**
     * Gets indivdual addresses.
     *
     * @return array
     */
    public function getAddressesSeparated($filterExhibition = null, $linkPlace = false, $returnStructure = false)
    {
        $addresses = $this->buildAddresses($this->addresses, false, $filterExhibition, $linkPlace, $returnStructure);

        if (!$returnStructure) {
            // lookup exhibitions
            for ($i = 0; $i < count($addresses); $i++) {
                $addresses[$i]['exhibitions'] = !empty($addresses[$i]['id_exhibitions'])
                    ? $this->getExhibitions(-1, $addresses[$i]['id_exhibitions'])
                    : [];
            }
        }

        return $addresses;
    }

    /**
     * Gets birthPlace info
     *
     */
    public function getBirthPlaceInfo($locale = 'en')
    {
        if (false && !is_null($this->birthPlace)) {
            return self::buildPlaceInfo($this->birthPlace, $locale);
        }

        /*
        $placeInfo = self::buildPlaceInfoFromEntityfacts($this->getEntityfacts($locale), 'placeOfBirth');
        if (!empty($placeInfo)) {
            return $placeInfo;
        }
        */

        if (!empty($this->birthPlaceLabel)) {
            return [
                'name' => $this->birthPlaceLabel,
            ];
        }
    }

    /**
     * Sets deathPlace.
     *
     * @param Place $deathPlace
     *
     * @return $this
     */
    public function setDeathPlace(/* Place */ $deathPlace = null)
    {
        $this->deathPlace = $deathPlace;

        return $this;
    }

    /**
     * Gets deathPlace.
     *
     * @return Place
     */
    public function getDeathPlace()
    {
        return $this->deathPlace;
    }

    /**
     * Gets deathPlace.
     *
     * @return string
     */
    public function getDeathPlaceLabel()
    {
        return $this->deathPlaceLabel;
    }

    /**
     * Gets deathPlace info
     *

src/Controller/PersonController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

use Doctrine\ORM\EntityManagerInterface;

use Knp\Component\Pager\PaginatorInterface;

/**
 *
 */
class PersonController
extends BaseController
{
    protected $pageSize = 100;

    /**
     * @Route("/person", name="person-index")
     */
    public function indexAction(Request $request,
                                EntityManagerInterface $entityManager,
                                PaginatorInterface $paginator,
                                TranslatorInterface $translator)
    {
        $qb = $entityManager
            ->createQueryBuilder();

        $qb->select([
                'P',
                "CONCAT(COALESCE(P.familyName,P.givenName), ' ', COALESCE(P.givenName, '')) HIDDEN nameSort"
            ])
            ->distinct()
            ->from('\App\Entity\Person', 'P')
            ->where('P.status IN (0,1)')
            ->orderBy('nameSort')
            ;

        $pagination = $this->buildPagination($request, $paginator, $qb->getQuery(), [
            // the following leads to wrong display in combination with our
            // helper.pagination_sortable()
            // 'defaultSortFieldName' => 'nameSort', 'defaultSortDirection' => 'asc',
        ]);

        return $this->render('Person/index.html.twig', [
            'pageTitle' => $translator->trans('Persons'),
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/person/ulan/{ulan}.jsonld", requirements={"ulan"="[0-9]+"}, name="person-by-ulan-jsonld")
     * @Route("/person/ulan/{ulan}", requirements={"ulan"="[0-9]+"}, name="person-by-ulan")
     * @Route("/person/gnd/{gnd}.jsonld", requirements={"gnd"="[0-9xX]+"}, name="person-by-gnd-jsonld")
     * @Route("/person/gnd/{gnd}", requirements={"gnd"="[0-9xX]+"}, name="person-by-gnd")
     * @Route("/person/{id}.jsonld", name="person-jsonld", requirements={"id"="\d+"})
     * @Route("/person/{id}", name="person", requirements={"id"="[^\/]+"})
     */
    public function detailAction(Request $request, EntityManagerInterface $entityManager,
                                 $id = null, $ulan = null, $gnd = null)
    {
        $criteria = new \Doctrine\Common\Collections\Criteria();

        if (!empty($id)) {
            $criteria->where($criteria->expr()->eq('identifier', $id));
        }
        else if (!empty($ulan)) {
            $criteria->where($criteria->expr()->eq('ulan', $ulan));
        }
        else if (!empty($gnd)) {
            $criteria->where($criteria->expr()->eq('gnd', $gnd));
        }
        else {
            return $this->redirectToRoute('person-index');
        }

        $criteria->andWhere($criteria->expr()->neq('status', -1));

        $personRepo = $entityManager
                ->getRepository('App\Entity\Person');
        $persons = $personRepo->matching($criteria);

        if (0 == count($persons)) {
            return $this->redirectToRoute('person-index');
        }

        $person = $persons[0];
        // $person->setDateModified(\App\Search\PersonListBuilder::fetchDateModified($entityManager->getConnection(), $person->getId()));

        $locale = $request->getLocale();
        if (in_array($request->get('_route'), [ 'person-jsonld', 'person-by-ulan-json', 'person-by-gnd-jsonld' ])) {
            return new JsonLdResponse($person->jsonLdSerialize($locale));
        }

        $routeName = 'person';
        $routeParams = [ 'id' => $person->getId() ];

        /*
        if (!empty($person->getUlan())) {
            $routeName = 'person-by-ulan';
            $routeParams = [ 'ulan' => $person->getUlan() ];
        }
        else if (!empty($person->getGnd())) {
            $routeName = 'person-by-gnd';
            $routeParams = [ 'gnd' => $person->getGnd() ];
        }
        */

        return $this->render('Person/detail.html.twig', [
            'pageTitle' => $person->getFullname(true), // TODO: lifespan in brackets
            'person' => $person,
            'pageMeta' => [
                // 'jsonLd' => $person->jsonLdSerialize($locale),
                // 'og' => $this->buildOg($person, $routeName, $routeParams),
                // 'twitter' => $this->buildTwitter($person, $routeName, $routeParams),
            ],
        ]);
    }

    /**
     * @Route("/person/gnd/beacon", name="person-gnd-beacon")
     *
     * Provide a BEACON file as described in
     *  https://de.wikipedia.org/wiki/Wikipedia:BEACON
     */
    public function gndBeaconAction(EntityManagerInterface $entityManager, TranslatorInterface $translator, \Twig\Environment $twig)
    {
        $ret = '#FORMAT: BEACON' . "\n"
             . '#PREFIX: http://d-nb.info/gnd/'
             . "\n";
        $ret .= sprintf('#TARGET: %s/gnd/{ID}',
                        $this->generateUrl('person-index', [], \Symfony\Component\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_URL))
              . "\n";

        $globals = $twig->getGlobals();

        $ret .= '#NAME: ' . /** @ignore */$translator->trans($globals['site_name'], [], 'additional')
              . "\n";
        // $ret .= '#MESSAGE: ' . "\n";

        $repo = $entityManager
                ->getRepository('App\Entity\Person');

        $query = $repo
                ->createQueryBuilder('P')
                ->where('P.status >= 0')
                ->andWhere('P.gnd IS NOT NULL')
                ->orderBy('P.gnd')
                ->getQuery()
                ;

        foreach ($query->execute() as $actor) {
            $ret .=  $actor->getGnd() . "\n";
        }

        return new Response($ret, Response::HTTP_OK, [
            'Content-Type' => 'text/plain; charset=UTF-8',
        ]);
    }
}

templates/Person/detail.html.twig
{% extends 'Base/base.html.twig' %}

{% import 'Shared/helper.html.twig' as helper %}
{% import 'Shared/map-leaflet.html.twig' as map %}

{% block head %}
    {{ map.head() }}

    <!-- https://verbundwiki.gbv.de/display/VZG/SeeAlso -->
    <script src="{{ app.request.basepath }}/js/seealso.js"></script>
    <script>
        var service = new SeeAlsoCollection();
        service.services = {
            'pndaks' : new SeeAlsoService('https://beacon.findbuch.de/seealso/pnd-aks/-lemo@ap/-dome')
        };
        service.views = {
            'seealso-ul' : new SeeAlsoUL({
                linkTarget: '_blank',
                maxItems: 100
            })
        };
        service.replaceTagsOnLoad();
    </script>
{% endblock %}

{% block body %}
    {{ helper.breadcrumb([ { label: 'Look-up' }, { route: app.request.attributes.get('_route'), label: 'Persons'} ]) }}

    <h1>{{ person.fullname(true) }}</h1>

    <div class="col-sm-8 col-lg-9">
        <div class="container-fluid p-0">
            {% if person.disambiguatingDescription is not empty %}
                <p>{{ person.disambiguatingDescription|nl2br }}</p>
            {% endif %}
            <dl class="row">
            {% if person.gender is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Gender'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">{{ person.genderLabel|trans }}</dd>
            {% endif %}
            {% if person.honorificPrefix is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Academic Title'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">{{ person.honorificPrefix }}</dd>
            {% endif %}
            {% if person.alternateName is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Alternate Name(s)'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">{{ person.alternateName|nl2br }}</dd>
            {% endif %}
            {% if person.hasOccupation is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Occupation'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">{{ person.hasOccupation }}</dd>
            {% endif %}
            {% set birthPlace = person.birthPlaceInfo(app.request.locale) %}
            {% if birthPlace is not empty or person.birthDate is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Born'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">
                    {{ person.birthDate -}}
                    {% if birthPlace is not empty %}{% if person.birthDate is not empty %}{{- ',' }}{% endif %}
                        {% if false and birthPlace.id is defined and birthPlace.id is not empty %}
                            <a href="{% if birthPlace.tgn is not empty %}{{ path('place-by-tgn', { 'tgn' : birthPlace.tgn }) }}{% else %}{{ path('place', { 'id' : birthPlace.id }) }}{% endif %}">
                            {{ birthPlace['name'] }}
                            </a>
                        {% else %}
                            {{ birthPlace['name'] }}
                        {% endif %}
                    {% endif %}
                </dd>
            {% endif %}
            {% set deathPlace = person.deathPlaceInfo(app.request.locale) %}
            {% if deathPlace is not empty or person.deathDate is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Died'|trans }}:</dt>
                <dd class="col-sm-8 col-md-9">
                    {{ person.deathDate -}}
                    {% if deathPlace is not empty %}{% if person.deathDate is not empty %}{{- ',' }}{% endif %}
                        {% if false and deathPlace.id is defined and deathPlace.id is not empty %}
                            <a href="{% if deathPlace.tgn is not empty %}{{ path('place-by-tgn', { 'tgn' : deathPlace.tgn }) }}{% else %}{{ path('place', { 'id' : deathPlace.id }) }}{% endif %}">
                            {{ deathPlace['name'] }}
                            </a>
                        {% else %}
                            {{ deathPlace['name'] }}
                        {% endif %}
                    {% endif %}
                </dd>
            {% endif %}
            {#% if person.description is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'Description'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">{{ person.description|nl2br }}</dd>
            {% endif %#}
            {% if person.url is not empty %}
                <dt class="col-sm-4 col-md-3">{{ 'URL'|trans }}</dt>
                <dd class="col-sm-8 col-md-9">{{ person.url| converturls  }}</dd>
            {% endif %}
            </dl>
        </div>
        {#{ dump(person) }#}
    </div>

    <div class="col-sm-4 col-lg-3">
        {% if person.gnd is not empty %}
            <h3>{{ 'Integrated Authority File'|trans }}
                <a href="https://d-nb.info/gnd/{{ person.gnd }}" target="_blank">{{ person.gnd }}</a>
            </h3>
            <div title="{{ person.gnd }}" class="pndaks seealso-ul"></div>
        {% endif %}

        {% if person.wikidata is not empty %}
            <h3>{{ 'Wikidata'|trans }}
                <small class="text-muted"><a href="https://www.wikidata.org/wiki/{{ person.wikidata }}" target="_blank">{{ person.wikidata }}</a></small>
            </h3>
        {% endif %}

    </div>
{% endblock %}

templates/Person/index.html.twig
{% extends 'Base/base.html.twig' %}

{% import 'Shared/helper.html.twig' as helper %}

{% block body %}
    <h1>{{ 'Persons'|trans }}</h1>
    <div class="col">
    {#
    <form method="get" action="{{ path(app.request.attributes.get('_route')) }}">
        <div class="form-group">
            {{ form_rest(form) }}
            <!--<button type="submit" class="btn btn-primary">{{ 'Search'|trans }}</button>-->
        </div>
    </form>
    #}

    {% if pagination.getTotalItemCount > 0 %}
        {% if pagination.page > 1 %}
        {# display navigation #}
        {{ knp_pagination_render(pagination) }}
        {% endif %}

        {% set last_initial = '' %}
        {% for row in pagination %}
            {% set initial = row.familyName|slug|first|upper %}
            {% if initial != last_initial %}
                <h2 class="initial">{{ initial }}</h2>
                {% set last_initial = initial %}
            {% else %}
                <br />
            {% endif %}
            {% set icon = row.dataProviderIcon %}{% if icon is not empty %}<i class="fa-sharp fa-solid fa-{{ icon }}"></i> {% endif %} <a href="{{ path('person', { 'id': row.identifier }) }}">{{ row.fullName }}</a>
            {% if row.birthDate is not empty or row.deathDate is not empty %}
            ({% if row.birthDate is not empty %}{{ row.birthDate }}{% endif %}-{% if row.deathDate is not empty %}{{ row.deathDate }}{% endif %})
            {% endif %}
            <span class="text-muted">{{ row.disambiguatingDescription }}</span>
        {% endfor %}

        {# display navigation #}
        {{ knp_pagination_render(pagination) }}
    {% else %}
        {{ 'No matching persons found'|trans }}
    {% endif %}
    </div>
{% endblock %}